[package]
name = "gurk"
description = "Signal messenger client for terminal"
version = "0.2.2"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"
keywords = ["signal", "tui"]
repository = "https://github.com/boxdot/gurk-rs"
license = "AGPL-3.0-only"
categories = ["command-line-utilities"]
resolver = "2"

[workspace]
members = ["xtask"]

[profile.dev.package.miniz_oxide]
# This speeds up `cargo xtask dist`.
opt-level = 3

[profile.release]
debug = 0
lto = "thin"

[dependencies]
presage = { git = "https://github.com/whisperfish/presage.git", rev = "4b3457f" }
# not used directly, but specified here to fix the commit for cargo install
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "b0f5d4f" }
libsignal-service-hyper = { git = "https://github.com/whisperfish/libsignal-service-rs.git", rev = "b0f5d4f" }
libsignal-protocol = { git = "https://github.com/signalapp/libsignal-client", rev = "228cb02" }

anyhow = "1.0.45"
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["serde"] }
crossterm = { version = "0.22.1", features = ["event-stream"] }
derivative = "2.2.0"
dirs = "4.0.0"
emoji = "0.2.1"
gh-emoji = "1.0.6"
hostname = "0.3.1"
itertools = "0.10.1"
log = "0.4.14"
log-panics = "2.0.0"
log4rs = "1.0.0"
mime_guess = "2.0.3"
notify-rust = "4.5.5"
opener = "0.5.0"
phonenumber = "0.3.1"
regex-automata = "0.1.10"
scopeguard = "1.1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
structopt = "0.3.25"
textwrap = "0.14.2"
tokio = { version = "1.14.0", default-features = false, features = ["rt-multi-thread", "macros", "net", "time"] }
tokio-stream = "0.1.8"
toml = "0.5.8"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
unicode-width = "0.1.9"
uuid = "0.8.2"
whoami = "1.2.0"

[dev-dependencies]
tempfile = "3.2.0"
uuid = { version = "0.8.2", features = ["v4"] }

# [patch."https://github.com/whisperfish/presage.git"]
# presage = { path = "../presage" }

# [patch."https://github.com/whisperfish/libsignal-service-rs"]
# libsignal-service = { path = "../libsignal-service-rs/libsignal-service" }
# libsignal-service-hyper = { path = "../libsignal-service-rs/libsignal-service-hyper" }

# [patch."https://github.com/signalapp/libsignal-client"]
# libsignal-protocol = { path = "../libsignal-client/rust/protocol" }
